[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["https"]

[functions."kite"]
  timeout = 26

[functions."auth"]
  timeout = 15

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nse"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
